# Baseline UAV Swarm Configuration
# No attacks - establishes clean baseline behavior

experiment_name: "baseline_swarm_50uavs"
random_seed: 42
swarm_size: 50
comm_range: 100.0  # meters
simulation_duration: 60.0  # seconds
update_frequency: 1.0  # Hz (1 update per second)

# No attack scenario
attack_scenario: null

# No cryptographic defense for baseline
enable_crypto: false

# No detection methods for baseline (just observation)
detection_methods: []

# Output directory
output_dir: "results/baseline_swarm"

