# Coordinated Multi-Spoofer Attack Configuration
# Injects coordinated phantom UAVs moving in formation

experiment_name: "coordinated_attack_circle_formation"
random_seed: 42
swarm_size: 50
comm_range: 100.0  # meters
simulation_duration: 120.0  # seconds
update_frequency: 1.0  # Hz

# Coordinated attack scenario
attack_scenario:
  attack_type: "coordinated"
  start_time: 30.0  # Start attack at t=30s
  duration: 60.0    # Attack lasts 60 seconds
  phantom_count: 8  # 8 phantoms in formation
  coordination_pattern: "circle"  # Circle formation

# No cryptographic defense
enable_crypto: false

# Detection methods to evaluate
detection_methods:
  - "spectral"
  - "centrality"

# Output directory
output_dir: "results/coordinated_attack"

