# Cryptographic Defense Configuration
# Uses Ed25519 signing to authenticate Remote ID messages

experiment_name: "crypto_defense_phantom_attack"
random_seed: 42
swarm_size: 50
comm_range: 100.0  # meters
simulation_duration: 120.0  # seconds
update_frequency: 1.0  # Hz

# Phantom attack scenario
attack_scenario:
  attack_type: "phantom"
  start_time: 30.0
  duration: 60.0
  phantom_count: 5

# Enable cryptographic defense
enable_crypto: true

# Crypto detector for verification
detection_methods:
  - "crypto"

# Output directory
output_dir: "results/crypto_defense"

