# Phantom UAV Attack Configuration
# Injects 5 phantom UAVs into a 50-UAV swarm

experiment_name: "phantom_attack_5_phantoms"
random_seed: 42
swarm_size: 50
comm_range: 100.0  # meters
simulation_duration: 120.0  # seconds
update_frequency: 1.0  # Hz

# Phantom attack scenario
attack_scenario:
  attack_type: "phantom"
  start_time: 30.0  # Start attack at t=30s
  duration: 60.0    # Attack lasts 60 seconds
  intensity: 0.1
  phantom_count: 5  # Inject 5 phantom UAVs

# No cryptographic defense
enable_crypto: false

# Detection methods to evaluate
detection_methods:
  - "spectral"
  - "centrality"

# Output directory
output_dir: "results/phantom_attack"

