# Position Falsification Attack Configuration
# Compromises 15% of UAVs to report false GPS positions

experiment_name: "position_falsification_15pct"
random_seed: 42
swarm_size: 50
comm_range: 100.0  # meters
simulation_duration: 120.0  # seconds
update_frequency: 1.0  # Hz

# Position falsification attack
attack_scenario:
  attack_type: "position"
  start_time: 30.0  # Start attack at t=30s
  duration: 60.0    # Attack lasts 60 seconds
  intensity: 0.15   # 15% of UAVs compromised
  falsification_magnitude: 75.0  # Offset by up to 75 meters

# No cryptographic defense
enable_crypto: false

# Detection methods to evaluate
detection_methods:
  - "spectral"
  - "centrality"

# Output directory
output_dir: "results/position_spoof"

